title: Hello, world! I'm  Kbloider
description: > # this means to ignore newlines until "baseurl:"
  Know what's now. Know what's next.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kbloider # add your name
author-img: kb7.jpg # add your photo
about-author: I am a web developer focusing on back-end development. Know what's now. Know what's next. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kbloider # add your Github handle
social-linkedin: # add your Linkedin handle
social-email:  kbloider@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
